BoxLayout:
    orientation: 'horizontal'
    Button:
        text: 'G'
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            orientation: 'horizontal'
            Button:
                text: 'E'
            Button:
                text: 'L'
            Button
                text: 'N'
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'D'
            Button
                text: 'J'




